### ISSUE TITLE
feat: Landing Page에 Glassmorphism UI 적용

### ISSUE THREAD

**Issue by PortalCube** [PortalCube/SmartLEAD-Plus#10]
### 라이트 모드
![v2-day-test](https://github.com/PortalCube/SmartLEAD-Plus/assets/35104213/c56349d6-1d07-44cb-a26c-79e6253e3c3e)

### 다크 모드
![v2-night-test](https://github.com/PortalCube/SmartLEAD-Plus/assets/35104213/30084c5e-e251-4192-a6f8-9f2faa01c8ae)

현재 SmartLEAD 디자인은 꽤나 단조로운 톤을 적용한 디자인으로 구성되어있음. 사실 디자인이 나쁜건 아닌데, 맨날 맨날 보는 화면이니 만큼 매일 매일 신선한 느낌을 주면 UX에 좋지 않을까 싶어서 Landing Page (메인 페이지)에 랜덤한 월페이퍼 이미지를 입히는 기능을 추가하고자 함. (약간 bing이랑 비슷한 느낌 https://www.bing.com/ )

여기에 더불어, 배경화면이 매일 새롭게 변경되므로 Landing Page의 디자인은 글래스모피즘을 적용하여 각 요소에 투명도를 적용, 배경이 비치도록 구성하려고 함.

## TODO

* [ ] UI 디자인 & 기획 마무리
* [x] Unsplash의 서비스를 이용하여 Landing Page에 매일 랜덤한 이미지 불러오는 기능 추가
* [ ] 라이트 모드 / 다크 모드 선택 기능 추가
  * 어쩌면 낮 시간에는 라이트모드, 밤 시간에는 다크모드로 해도 괜찮을듯?
